name: Java CI with Gradle
concurrency: production
on:
  push:
    branches: [ "production" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      #      - name: Whoami
      #        run: whoami
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make gradlew Executable
        run: chmod +x ./gradlew
      - name: Gradle Build
        run: ./gradlew build
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= DOCKER IMAGE PUSH START =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#      - name: Docker Login                                                                                     #
#        uses: docker/login-action@v2.1.0                                                                       #
#        with:                                                                                                  #
#          username: ${{ secrets.NEXUS_USERNAME }}                                                              #
#          password: ${{ secrets.NEXUS_PASSWORD }}                                                              #
#          registry: ${{ secrets.NEXUS_DOCKER_URL }}                                                            #
#      - name: Push Docker image                                                                                #
#        uses: docker/build-push-action@v3.2.0                                                                  #
#        with:                                                                                                  #
#          push: true                                                                                           #
#          context: your-context                                                                                #
#          tags: my-server:port/path:latest                                                                     #
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  DOCKER IMAGE PUSH END  =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= DEPLOY PLUGIN START =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#      - name: Deploy                                                                                           #
#        run: mkdir -p /path/to/plugins && cp build/libs/SamplePlugin                                           #
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  DEPLOY PLUGIN END  =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=